# codegen.toml for sensors

# model sources
[[models]]
path = "."
files = [ "display.smithy" ]

[[models]]
url = "https://wasmcloud.github.io/interfaces/idl/org.wasmcloud"
files = [ "wasmcloud-core.smithy", "wasmcloud-model.smithy" ]


[tinygo]
output_dir = ""
formatter = [ "goimports", "-w" ]
files = [
    { path = "display.go", package="display", namespace = "org.wasmcloud.interface.display" },
]
